// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Microsoft.ML.Data;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<MLData.ModelInput, MLData.ModelOutput>()
    .FromFile("MLData.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});



app.MapGet("/predict",(string inputText) => {

        var sampleData = new MLData.ModelInput()
        {
            Col0 = inputText
        };
        var result = MLData.Predict(sampleData);
        // If Prediction is 1, sentiment is "Positive"; otherwise, sentiment is "Negative"
        var sentiment = result.PredictedLabel == 1 ? "Positive" : "Negative";
        Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");
    return $"Text: {sampleData.Col0}\nSentiment: {sentiment}";
    });
// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<MLData.ModelInput, MLData.ModelOutput> predictionEnginePool, MLData.ModelInput input) =>
        await Task.FromResult(predictionEnginePool.Predict(input)));

// Run app
app.Run();
